### ISSUE TITLE
 Installation failure

### ISSUE THREAD

**Issue by soportesistemasrtq** [InfotelGLPI/shellcommands#13]
* Version of the plugin : 
2.3.0

* Version of your GLPI : 
9.5.2

* Steps to reproduce (which actions have you made) :
 - Copy the file to the server, in the path \ glpi \ plugins \
 - Unzip the file
 - Install plugin from marketplace
 - Activate plugin
 
* Expected result :
Activation successful

* Actual result :
Plugin prerequisites do not match, cannot be activated. This plugin requires GLPI> = 9.4.

* URL of the page :
Local server

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/79530408/108878020-ce034b80-75cd-11eb-8840-3bef31442522.png)

**Comment by NOSJulien** [comment]
We wait an update of this plugin but it's seems like abandoned...

**Comment by tsmr** [comment]
Plugin released https://github.com/InfotelGLPI/shellcommands/releases/tag/3.0.0
