### ISSUE TITLE
EVO : Ajouter l'element attaché 'Applicatif' / URL

### ISSUE THREAD

**Issue by EC2311** [InfotelGLPI/shellcommands#14]
Bonjour

On peut ajouter différents éléments dont ordinateur, telephone imprimante : ok

Il serait interessant de pouvoir attacher ce plugin à 'lapplicatif, afin de pouvoir pinguer l'applicatif (ex site web)

Dans le fichier inc/shellcommand.class.php : 
class PluginShellcommandsShellcommand extends CommonDBTM {

   static $types = ['Computer', 'NetworkEquipment', 'Peripheral',
                    'Phone', 'Printer', '**Appliance**'];

D'autre part, dans meme contexte ajouter la balise 'URL' afin de pouvoir pinguer le champ url spécifié dans l'applicatif.

Merci

**Comment by tsmr** [comment]
Bonne idée :)
Par contre il n'y a pas de champ 'Url' au niveau des applicatifs (vous avez le plugin webapplications d'activé ?)

**Comment by EC2311** [comment]
oui tout à fait, plugin webapplications activé.

**Comment by EC2311** [comment]
Bonjour

Pour des besoins internes, j'ai ajouté des champs supplémentaires de type URL (plugin fields)
Pourrait-on utiliser ce plugin avec ces champs annexes ?
