### ISSUE TITLE
Wake on Lan issue

### ISSUE THREAD

**Issue by husisusi** [InfotelGLPI/shellcommands#18]
* Version of the plugin : 4.0.1

* Version of your GLPI : 10.0.2

* Steps to reproduce (which actions have you made) :
Install Shellcommands plugin & enable it
Set up Wake on an to execute  /usr/bin/wakeonlan
Try to use it

* Expected result : OK Magic packet sending to cc:d9:ac:11:yx:xy

* Actual result : KO php errors

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/8606735/185799132-975ca72b-3bc0-4903-8535-8c6afab866d5.png)

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
PHP 8.1.8

The wakeonlan command works from terminal for all users.

My Configuration:
![image](https://user-images.githubusercontent.com/8606735/185799504-44df4c96-d927-4e05-90e6-9eba8365d715.png)

**Comment by husisusi** [comment]
Any idea?

**Comment by Chrisnet46** [comment]
Hi,

Same here.

GLPI 10.0.7
Plugin 4.0.1

**Comment by husisusi** [comment]
I found a solution!
Just delete "Wake on LAN" from "Shell Commands" and create it again.
Mine looks like this and it works:

 
![image](https://user-images.githubusercontent.com/8606735/236664465-4a980d0c-cd0f-4a78-9086-ff47d1237f8b.png)
