### ISSUE TITLE
Massiveexec doesn't work

### ISSUE THREAD

**Issue by stek6** [InfotelGLPI/shellcommands#5]
Hi,
- plugin Version 2.1.0
- GLPI 9.2.1
When i select some computers and launch "Command launch" action to send "Ping" command,  it doesn't happen anything. It appears only the popup with Operation successfully completed, but i don't see any output.
I can confirm that the plugin v.2.0 with glpi 9.1 worked perfectly.
Please help me. Thanks.

Regards

**Comment by amma35** [comment]
Hi, 
Plugin operation has not changed between versions 2.0.0 and 2.1.0.

Can you detail the parameters you put in the ping command? 
What results do you get?

**Comment by stek6** [comment]
Hi, 
the ping command is the default one without any different parameters, i've only associated the element "Computer" to it. 
From Glpi when i select some computers, go to Actions and select Command launch and Ping (the only shell command enabled) i see this output: 

but i can't see the output of multiple command launch. 
In plugin version 2.0 i see this output 

It seems that massivexec.php doesn't run. 
Please help. 

Regards

**Comment by stek6** [comment]
Sorry, 
i attach images 

Regards 


Da: "Stefano Boretti" <stefano.boretti@yacme.com> 
A: "InfotelGLPI/shellcommands" <reply@reply.github.com> 
Cc: "InfotelGLPI/shellcommands" <shellcommands@noreply.github.com>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 6 febbraio 2018 17:26:30 
Oggetto: Re: [InfotelGLPI/shellcommands] Massiveexec doesn't work (#5) 

Hi, 
the ping command is the default one without any different parameters, i've only associated the element "Computer" to it. 
From Glpi when i select some computers, go to Actions and select Command launch and Ping (the only shell command enabled) i see this output: 

but i can't see the output of multiple command launch. 
In plugin version 2.0 i see this output 

It seems that massivexec.php doesn't run. 
Please help. 

Regards 

Da: "Amandine Manceau" <notifications@github.com> 
A: "InfotelGLPI/shellcommands" <shellcommands@noreply.github.com> 
Cc: "stek6" <stefano.boretti@yacme.com>, "Author" <author@noreply.github.com> 
Inviato: Martedì, 6 febbraio 2018 13:47:11 
Oggetto: Re: [InfotelGLPI/shellcommands] Massiveexec doesn't work (#5) 



Hi, 
Plugin operation has not changed between versions 2.0.0 and 2.1.0. 

Can you detail the parameters you put in the ping command? 
What results do you get?

**Comment by stek6** [comment]
Hi, the ping command is the default one without any different parameters, i've only associated the element "Computer" to it. From Glpi when i select some computers, go to Actions and select Command launch and Ping (the only shell command enabled) i see this output
![output_not_working](https://user-images.githubusercontent.com/36170678/36354606-54303c28-14d7-11e8-9c66-e248a57606ad.png)

but i can't see the output of multiple command launch as in the previous plugin version.
![output_ok](https://user-images.githubusercontent.com/36170678/36354610-5d093228-14d7-11e8-8a6b-8242f5caf9ec.JPG)

It seems that massivexec.php doesn't run. 
Please help. 

Regards
